version: "3"
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://tinker:password@db:5432/tinker
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: tinker
    depends_on:
      - db
  db:
    image: jarednaylor/postgres-jwt:postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tinker
      POSTGRES_USER: tinker
      POSTGRES_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
